// Exhibit records. UI components never hardcode creator data: add, edit or publish records here.
//
// Fields
//   id, slug              stable identifiers (slug is used in /exhibition/exhibits/<slug>)
//   title, creator        what is shown as the heading and the person/organisation
//   category              one of the Hall of Fame category slugs (content/exhibition/categories.js)
//   achievement           the one-line claim, kept faithful to the source
//   description           optional longer text (omit when unavailable)
//   figure                optional { value, label } shown prominently
//   date, datePrecision   ISO-style partial date ("2023", "2025-09", "2017-08-21", "2016-10-11T14:21") + year|month|day|minute
//   image                 optional { src, alt }
//   media                 optional array of { type: "image"|"video", src, alt, caption }
//   relatedExhibits       optional array of slugs
//   sourceNote            internal; only shown in team preview
//   verificationStatus    "verified" | "needs_verification" (internal)
//   publicationStatus     "published" | "ready" | "awaiting_copy" | "awaiting_asset" | "needs_verification" | "superseded"
//                         Only "published" is public; everything else shows in team preview only.
//   sortOrder             order within a category
//   leaderOf, award       optional extra labels
export const exhibits = [
  {"id":"ex-001","slug":"funky-collections","title":"Funky Collections","category":"fastest-sales","creator":"Funky Collections","achievement":"In 2023, Funky Collections achieved five-figure sales in USD within seven hours of launching its first product.","figure":{"value":"7 hours","label":"to five-figure USD sales"},"date":"2023","datePrecision":"year","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":1},
  {"id":"ex-002","slug":"oluwafemi-williams","title":"Oluwafemi Williams","category":"fastest-sales","creator":"Oluwafemi Williams","achievement":"Got 100 unique customers in 10 minutes.","figure":{"value":"10 minutes","label":"to 100 unique customers"},"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":2},
  {"id":"ex-003","slug":"tolu-falode","title":"Tolu Falode","category":"consistency-streak","creator":"Tolu Falode","achievement":"Made a sale every month for eight years.","figure":{"value":"8 years","label":"of monthly sales"},"relatedExhibits":["creator-of-the-year-2017"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":3},
  {"id":"ex-004","slug":"coach-dino","title":"Coach Dino","category":"consistency-streak","creator":"Coach Dino","achievement":"Made a sale every day for 1,110 days straight.","figure":{"value":"1,110 days","label":"of daily sales"},"relatedExhibits":["earn-in-foreign-currencies-blueprint"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":4},
  {"id":"ex-005","slug":"isi-benedicta-institute","title":"Isi Benedicta Institute","category":"top-monthly-sales","creator":"Isi Benedicta Institute","achievement":"Achieved six-figure sales in USD in a single month, September 2025.","figure":{"value":"Six figures","label":"USD in one month"},"date":"2025-09","datePrecision":"month","relatedExhibits":["record-highest-monthly-revenue"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":5},
  {"id":"ex-006","slug":"orient-graphic-skills","title":"Orient Graphic Skills","category":"top-monthly-sales","creator":"Orient Graphic Skills","achievement":"Sold 8,129 units of a single product in January 2026.","figure":{"value":"8,129","label":"units of a single product"},"date":"2026-01","datePrecision":"month","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":6},
  {"id":"ex-007","slug":"chinecherem-udegbunam","title":"Chinecherem Udegbunam","category":"global-reach","creator":"Chinecherem Udegbunam","achievement":"Sold products to customers in 100 countries.","figure":{"value":"100","label":"countries"},"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":7},
  {"id":"ex-008","slug":"felix-ohaeri","title":"Felix Ohaeri","category":"global-reach","creator":"Felix Ohaeri","achievement":"Sold one AI training product in 91 countries.","figure":{"value":"91","label":"countries, one AI training product"},"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":8},
  {"id":"ex-009","slug":"affiliate-marketing-sales-secret","title":"Affiliate Marketing Sales Secret (AMSS)","category":"product-excellence","creator":"Victor Nathel","achievement":"Recorded as the best-selling digital product by revenue.","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":9},
  {"id":"ex-010","slug":"simplified-online-survey-guide","title":"SIMPLIFIED ONLINE SURVEY GUIDE (GET PAY IN POUNDS)","category":"product-excellence","creator":"CentralAfCo™","achievement":"Recorded as the most purchased digital product, with 17,472 sales.","figure":{"value":"17,472","label":"sales"},"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":10},
  {"id":"ex-011","slug":"vicky-betran","title":"Vicky Betran","category":"affiliate-legend","creator":"Vicky Betran","achievement":"Holds the recorded all-time record for affiliate commission earnings, reaching a six-figure milestone in USD.","figure":{"value":"Six figures","label":"USD in affiliate commissions"},"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":11},
  {"id":"ex-012","slug":"adebisi-odunayo-temitope","title":"Adebisi Odunayo Temitope","category":"affiliate-legend","creator":"Adebisi Odunayo Temitope","achievement":"Referred 6,497 buyers to Selar creators, the highest number recorded by a Selar affiliate.","figure":{"value":"6,497","label":"buyers referred"},"sourceNote":"Source qualifies this as the highest number recorded by a Selar affiliate in the supplied milestones document.","verificationStatus":"verified","publicationStatus":"published","sortOrder":12},
  {"id":"ex-013","slug":"muyiwa","title":"Muyiwà","category":"selar-firsts","creator":"Muyiwà","achievement":"First creator to sign up on Selar, on 11 October 2016 at 14:21.","date":"2016-10-11T14:21","datePrecision":"minute","relatedExhibits":["ut-first-account","creator-of-the-year-2016"],"sourceNote":"CONFLICT: the Hall of Fame record names Muyiwà as the first creator to sign up (11 Oct 2016, 14:21). A separate historical record in the same PDF names UT (Dotunj_afxc) as the platform's first account (9 Oct 2016, 09:03). Not reconciled; awaiting confirmation from the source owner.","verificationStatus":"needs_verification","publicationStatus":"needs_verification","sortOrder":13},
  {"id":"ex-014","slug":"ut-first-account","title":"UT (Dotunj_afxc)","category":"selar-firsts","creator":"UT (username Dotunj_afxc)","achievement":"Registered the platform’s first account on 9 October 2016 at 09:03.","date":"2016-10-09T09:03","datePrecision":"minute","relatedExhibits":["muyiwa"],"sourceNote":"CONFLICT: see the Muyiwà record. This historical record (first account) differs from the Hall of Fame record (first creator). Not reconciled; awaiting confirmation from the source owner.","verificationStatus":"needs_verification","publicationStatus":"needs_verification","sortOrder":14},
  {"id":"ex-015","slug":"temitope-agbana","title":"Temitope Agbana","category":"selar-firsts","creator":"Temitope Agbana","achievement":"Recorded as the first affiliate to earn a commission, on 21 August 2017.","date":"2017-08-21","datePrecision":"day","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":15},
  {"id":"ex-016","slug":"che-george-neba","title":"Che George Neba","category":"selar-firsts","creator":"Che George Neba","achievement":"Recorded as the first Francophone creator, from Cameroon, on 5 June 2021.","date":"2021-06-05","datePrecision":"day","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":16},
  {"id":"ex-017","slug":"quran-recitation-masterclass","title":"Quran Recitation Masterclass","category":"category-leaders","creator":"The Knowledge Bank","achievement":"Category leader for Faith.","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":17,"leaderOf":"Faith"},
  {"id":"ex-018","slug":"earn-in-foreign-currencies-blueprint","title":"Earn In Foreign Currencies Blueprint","category":"category-leaders","creator":"Coach Dino","achievement":"Category leader for Business.","relatedExhibits":["record-longest-daily-sales-streak"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":18,"leaderOf":"Business"},
  {"id":"ex-019","slug":"make-him-worship-you","title":"MAKE HIM WORSHIP YOU","category":"category-leaders","creator":"Atewo Laolu-Ogunniyi","achievement":"Category leader for Love and Relationships.","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":19,"leaderOf":"Love and Relationships"},
  {"id":"ex-020","slug":"salem-king","title":"Salem King","category":"ecosystem-impact","creator":"Salem King","achievement":"Recipient of the Community Builder Award.","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":20,"award":"Community Builder Award"},
  {"id":"ex-021","slug":"toyin-omotoso","title":"Toyin Omotoso","category":"ecosystem-impact","creator":"Toyin Omotoso","achievement":"Recipient of the Affiliate Mentor Award.","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":21,"award":"Affiliate Mentor Award"},
  {"id":"ex-022","slug":"creator-of-the-year-2016","title":"Creator of the Year 2016","category":"creator-of-the-year","creator":"Muyiwà","achievement":"Muyiwà was recognised as Creator of the Year for 2016.","figure":{"value":"2016","label":"Creator of the Year"},"date":"2016","datePrecision":"year","relatedExhibits":["muyiwa"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":22},
  {"id":"ex-023","slug":"creator-of-the-year-2017","title":"Creator of the Year 2017","category":"creator-of-the-year","creator":"Tolu Falode","achievement":"Tolu Falode was recognised as Creator of the Year for 2017.","figure":{"value":"2017","label":"Creator of the Year"},"date":"2017","datePrecision":"year","relatedExhibits":["tolu-falode"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":23},
  {"id":"ex-024","slug":"creator-of-the-year-2018","title":"Creator of the Year 2018","category":"creator-of-the-year","creator":"Tolu Falode","achievement":"Tolu Falode was recognised as Creator of the Year for 2018.","figure":{"value":"2018","label":"Creator of the Year"},"date":"2018","datePrecision":"year","relatedExhibits":["tolu-falode"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":24},
  {"id":"ex-025","slug":"creator-of-the-year-2019","title":"Creator of the Year 2019","category":"creator-of-the-year","creator":"Jay Becks™","achievement":"Jay Becks™ was recognised as Creator of the Year for 2019.","figure":{"value":"2019","label":"Creator of the Year"},"date":"2019","datePrecision":"year","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":25},
  {"id":"ex-026","slug":"creator-of-the-year-2020","title":"Creator of the Year 2020","category":"creator-of-the-year","creator":"Tricia Biz","achievement":"Tricia Biz was recognised as Creator of the Year for 2020.","figure":{"value":"2020","label":"Creator of the Year"},"date":"2020","datePrecision":"year","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":26},
  {"id":"ex-027","slug":"creator-of-the-year-2021","title":"Creator of the Year 2021","category":"creator-of-the-year","creator":"The Discovery Centre","achievement":"The Discovery Centre was recognised as Creator of the Year for 2021.","figure":{"value":"2021","label":"Creator of the Year"},"date":"2021","datePrecision":"year","relatedExhibits":["creator-of-the-year-2023"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":27},
  {"id":"ex-028","slug":"creator-of-the-year-2022","title":"Creator of the Year 2022","category":"creator-of-the-year","creator":"Taofeek Kareem","achievement":"Taofeek Kareem was recognised as Creator of the Year for 2022.","figure":{"value":"2022","label":"Creator of the Year"},"date":"2022","datePrecision":"year","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":28},
  {"id":"ex-029","slug":"creator-of-the-year-2023","title":"Creator of the Year 2023","category":"creator-of-the-year","creator":"The Discovery Centre","achievement":"The Discovery Centre was recognised as Creator of the Year for 2023.","figure":{"value":"2023","label":"Creator of the Year"},"date":"2023","datePrecision":"year","relatedExhibits":["creator-of-the-year-2021"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":29},
  {"id":"ex-030","slug":"creator-of-the-year-2024","title":"Creator of the Year 2024","category":"creator-of-the-year","creator":"The Maintenance Institute / Epsilon Reliability Solutions Limited","achievement":"The Maintenance Institute / Epsilon Reliability Solutions Limited was recognised as Creator of the Year for 2024.","figure":{"value":"2024","label":"Creator of the Year"},"date":"2024","datePrecision":"year","sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":30},
  {"id":"ex-031","slug":"creator-of-the-year-2025","title":"Creator of the Year 2025","category":"creator-of-the-year","creator":"Isi Benedicta Institute","achievement":"Isi Benedicta Institute was recognised as Creator of the Year for 2025.","figure":{"value":"2025","label":"Creator of the Year"},"date":"2025","datePrecision":"year","relatedExhibits":["isi-benedicta-institute"],"sourceNote":"Selar Exhibition Milestones.pdf (as supplied in the PRD, section 9).","verificationStatus":"verified","publicationStatus":"published","sortOrder":31},
];
