// GENERATED by scripts/import_records.py from https://records.selar.com/breakable-records. Do not edit by hand.
// Publication and verification decisions live in records-status.js. Re-run the script to refresh.
export const recordsMeta = {
  "source": "https://records.selar.com/breakable-records",
  "generatedAt": "2026-10-10T03:34:02Z",
  "count": 34
};

export const recordGroups = [
  {
    "slug": "records-speed",
    "title": "Fastest to Reach"
  },
  {
    "slug": "records-streaks",
    "title": "Streaks and Loyalty"
  },
  {
    "slug": "records-honour",
    "title": "Creator of the Year"
  },
  {
    "slug": "records-volume",
    "title": "Volume and Revenue"
  },
  {
    "slug": "records-firsts",
    "title": "Firsts on Selar"
  }
];

// Normalised creator name -> photo, collected from every place a creator appears on the site.
export const creatorPhotos = {
  "5starmums": "/exhibition/creators/5starmums-selar-com-20250513112654.jpg",
  "alpha kids mentorship": "/exhibition/creators/akuasafo-selar-com-20260210044749.jpg",
  "ayanime edem": "/exhibition/creators/ayanimeedem-selar-co-20220306033436.jpg",
  "ayomide daniel": "/exhibition/creators/hollygrafix-selar-co-20231221034321.jpg",
  "babafemi adebajo": "/exhibition/creators/babafemi-adebajo-selar-com-20260714031718.jpg",
  "benny growth hub": "/exhibition/creators/bennyexpression-selar-com-20260129095729.jpg",
  "bo brand": "/exhibition/creators/nwankwo-chinonso1-selar-com-20260613040236.jpg",
  "catalyst children network": "/exhibition/creators/catalystnetwork-selar-com-20250926012439.jpg",
  "centralafco": "/exhibition/creators/godfrey-mato1-selar-co-20231203050730.jpg",
  "chai with soulunraveled": "/exhibition/creators/chaiwithsoulunraveled-selar-co-20230225023056.jpg",
  "charisma secrets": "/exhibition/creators/charismasecrets-selar-com-20250527011426.jpg",
  "coach dino": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
  "colors of hope global": "/exhibition/creators/colorsofhopeglobal-selar-co-20230101102737.jpg",
  "dr. sam adeyemi": "/exhibition/creators/drsamadeyemi-selar-com-20260820105445.jpg",
  "emeka nobis": "/exhibition/creators/emekanobis-selar-co-20231225092830.jpg",
  "emisphere catering": "/exhibition/creators/aoh14ginfbfzxpdtxch9cvihjq7uea9gmqi2smbigsif-s96-c.jpg",
  "forxers": "/exhibition/creators/nzoputa-ezike1-selar-com-20250611070749.jpg",
  "frank itom": "/exhibition/creators/frank-itom1-selar-co-20240326071255.jpg",
  "gbolahan yussuf hammed": "/exhibition/creators/aitbvmnhiaxrmhhi4ity5lbsvdcni56nrbod2zdr-1nf-s96-c.jpg",
  "godwin edafe oghenekome": "/exhibition/creators/fxtradersdelight-selar-co-20221020081636.jpg",
  "habeebah cakes": "/exhibition/creators/habeebahcakes-selar-co-20240704091114.jpg",
  "hafusat jubreel": "/exhibition/creators/hafusat-jubreel1-selar-com-20250626082101.jpg",
  "houseofmascot": "/exhibition/creators/houseofmascot-selar-co-20220115033458.jpg",
  "ipnet global": "/exhibition/creators/ipnetglobal-selar-com-20250304120401.jpg",
  "irene pepple": "/exhibition/creators/aoh14girpdr8pl1gukhjj-3okq1gatr1qlvcvdeflt1far4-s96-c.jpg",
  "isaac oyedepo": "/exhibition/creators/isaac-oyedepo1-selar-com-20250312020328.jpg",
  "isi benedicta institute": "/exhibition/creators/isibenedicta-selar-co-20230417095955.jpg",
  "james karundu": "/exhibition/creators/jameskarundu-selar-co-20231222021403.jpg",
  "just us girls global network": "/exhibition/creators/just-us-girls1-selar-com-20250331101721.jpg",
  "kenny nwokoye": "/exhibition/creators/kennynwokoye-selar-co-20231220033832.jpg",
  "maltida oseze": "/exhibition/creators/maltida-oseze1-selar-com-20251213090837.jpg",
  "mentality with pk": "/exhibition/creators/mentality-with-pk1-selar-com-20250410022821.jpg",
  "naijasales maker": "/exhibition/creators/naijasalesmaker-selar-com-20261004080602.jpg",
  "nursetrendy": "/exhibition/creators/nursetrendy-selar-com-20260715040321.jpg",
  "oluwafemi williams": "/exhibition/creators/aoh14gjcgwmzuymyvwklndsfdmyjyghfvcl-p2j6egn2uhs-s96-c.jpg",
  "oreint graphic skills": "/exhibition/creators/salesaffilate-selar-com-20260118093828.jpg",
  "phoenixes city": "/exhibition/creators/phoenixescity-selar-com-20260922012048.jpg",
  "praise daniel": "/exhibition/creators/acg8ockcvmhi2-txz-qd2qalqtx3ctlb8527zrtk8xb4tzm0vr8wluhh-s96-c.jpg",
  "products by dele amaebite": "/exhibition/creators/deleamaebite-selar-co-20220820010236.jpg",
  "sisi yemmie": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
  "smart bride hub by pearls": "/exhibition/creators/faith-adeniyi2198938-selar-com-20260214092122.jpg",
  "smartphonephotographyboss": "/exhibition/creators/smartphonephotographyboss-selar-co-20221006093758.jpg",
  "supernatural marriage network": "/exhibition/creators/supernaturalmarriagenetwork-selar-com-20260727031631.jpg",
  "talk dirty online shop": "/exhibition/creators/copy-of-talkshop-20260303-220904-0000-20260811050319.jpg",
  "temitope akintoye (trendy courier)": "/exhibition/creators/temitopeakintoye-selar-co-20230827122043.jpg",
  "the discovery centre": "/exhibition/creators/thediscoverycentre-selar-co-20230729052438.jpg",
  "the intentional parent academy": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
  "the pitch sthrim (survive, thrive, multiply)": "/exhibition/creators/acg8ocka1lc69lttty-iu-a2bhm7fox8wyjtcg8iejmhh7puza-s96-c.jpg",
  "tolu falode": "/exhibition/creators/tolu-selar-com-20251219093120.jpg",
  "unique affiliate community": "/exhibition/creators/maxdivine-selar-co-20220912113413.jpg",
  "victor nathel": "/exhibition/creators/victornathel-selar-co-20230406082832.jpg",
  "with chude": "/exhibition/creators/withchude-selar-com-20250903050354.jpg",
  "zarahdoughnuts": "/exhibition/creators/zarahdoughnuts-selar-co-20211222092715.jpg"
};

export const records = [
  {
    "id": "rec-001",
    "slug": "record-fastest-to-10k-in-revenue",
    "title": "Fastest to $10K in revenue",
    "category": "records-speed",
    "creator": "Just Us Girls Global Network",
    "achievement": "The shortest time from a creator's first sale to $10,000 in total revenue on Selar.",
    "description": "It is the first rung most creators aim for, which makes it the most contested record in the book — the margin at the top has narrowed every year since it was first set.",
    "figure": {
      "value": "1 Day",
      "label": "31 March 2025"
    },
    "photo": "/exhibition/creators/just-us-girls1-selar-com-20250331101721.jpg",
    "storeUrl": "https://selar.com/m/just-us-girls1",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Funky Collections",
        "figure": "3 Days",
        "date": "Aug 6, 2023",
        "photo": null,
        "storeUrl": "https://selar.com/m/funky-collections1"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Nelly Agbogu",
        "figure": "9 Days",
        "date": "Jan 14, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "MENtality With PK",
        "figure": "9 Days",
        "date": "Apr 18, 2025",
        "photo": "/exhibition/creators/mentality-with-pk1-selar-com-20250410022821.jpg",
        "storeUrl": "https://selar.com/m/mentality-with-pk1"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Discovery Centre",
        "figure": "10 Days",
        "date": "Mar 25, 2021",
        "photo": "/exhibition/creators/thediscoverycentre-selar-co-20230729052438.jpg",
        "storeUrl": "https://thediscoverycentre.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "31 March 2025",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 100,
    "date": "2025-03-31",
    "datePrecision": "day"
  },
  {
    "id": "rec-002",
    "slug": "record-fastest-to-50k-in-revenue",
    "title": "Fastest to $50K in revenue",
    "category": "records-speed",
    "creator": "Just Us Girls Global Network",
    "achievement": "The shortest time from first sale to $50,000 in total revenue.",
    "description": "Where the $10K record rewards a strong launch, this one rewards a creator who can hold that pace for weeks — most attempts stall in the second month.",
    "figure": {
      "value": "16 Days",
      "label": "15 April 2025"
    },
    "photo": "/exhibition/creators/just-us-girls1-selar-com-20250331101721.jpg",
    "storeUrl": "https://selar.com/m/just-us-girls1",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "BO BRAND",
        "figure": "19 Days",
        "date": "Oct 8, 2023",
        "photo": "/exhibition/creators/nwankwo-chinonso1-selar-com-20260613040236.jpg",
        "storeUrl": "https://Bomasterclass.selar.com/shop"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Tricia Biz",
        "figure": "23 Days",
        "date": "Aug 23, 2020",
        "photo": null,
        "storeUrl": "https://triciabiz.selar.com/shop"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Lanre Oluseye",
        "figure": "33 Days",
        "date": "Apr 18, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/lanre-oluseye2180159"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Nelly Agbogu",
        "figure": "41 Days",
        "date": "Feb 15, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      }
    ],
    "pastHolders": [],
    "displayDate": "15 April 2025",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 101,
    "date": "2025-04-15",
    "datePrecision": "day"
  },
  {
    "id": "rec-003",
    "slug": "record-fastest-to-100k-in-revenue",
    "title": "Fastest to $100K in revenue",
    "category": "records-speed",
    "creator": "BO BRAND",
    "achievement": "The shortest time from first sale to $100,000 in total revenue.",
    "description": "Only a handful of creators have ever reached it inside a year, and every holder so far has done it on the back of a catalogue rather than a single product.",
    "figure": {
      "value": "39 Days",
      "label": "28 October 2023"
    },
    "photo": "/exhibition/creators/nwankwo-chinonso1-selar-com-20260613040236.jpg",
    "storeUrl": "https://Bomasterclass.selar.com/shop",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Tricia Biz",
        "figure": "158 Days",
        "date": "Jan 5, 2021",
        "photo": null,
        "storeUrl": "https://triciabiz.selar.com/shop"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Fela Durotoye",
        "figure": "177 Days",
        "date": "Dec 18, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/Fela-Durotoye"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "SOLUTION INDUSTRY",
        "figure": "209 Days",
        "date": "Dec 22, 2022",
        "photo": null,
        "storeUrl": "https://selar.com/m/Sanixy001"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Discovery Centre",
        "figure": "216 Days",
        "date": "Oct 17, 2021",
        "photo": "/exhibition/creators/thediscoverycentre-selar-co-20230729052438.jpg",
        "storeUrl": "https://thediscoverycentre.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "28 October 2023",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 102,
    "date": "2023-10-28",
    "datePrecision": "day"
  },
  {
    "id": "rec-004",
    "slug": "record-fastest-to-250k-in-revenue",
    "title": "Fastest to $250K in revenue",
    "category": "records-speed",
    "creator": "BO BRAND",
    "achievement": "The shortest time from first sale to $250,000 in total revenue — the highest revenue milestone the Book of Records tracks.",
    "description": "It has changed hands less often than any other record here.",
    "figure": {
      "value": "271 Days",
      "label": "16 June 2024"
    },
    "photo": "/exhibition/creators/nwankwo-chinonso1-selar-com-20260613040236.jpg",
    "storeUrl": "https://Bomasterclass.selar.com/shop",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Learning  Lantern",
        "figure": "411 Days",
        "date": "Dec 15, 2025",
        "photo": null,
        "storeUrl": "https://selar.com/m/learning-lantern1"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "ForXers",
        "figure": "460 Days",
        "date": "Oct 1, 2025",
        "photo": "/exhibition/creators/nzoputa-ezike1-selar-com-20250611070749.jpg",
        "storeUrl": "https://ForXers.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Tricia Biz",
        "figure": "590 Days",
        "date": "Mar 13, 2022",
        "photo": null,
        "storeUrl": "https://triciabiz.selar.com/shop"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Discovery Centre",
        "figure": "693 Days",
        "date": "Feb 6, 2023",
        "photo": "/exhibition/creators/thediscoverycentre-selar-co-20230729052438.jpg",
        "storeUrl": "https://thediscoverycentre.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "16 June 2024",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 103,
    "date": "2024-06-16",
    "datePrecision": "day"
  },
  {
    "id": "rec-005",
    "slug": "record-fastest-to-100-customers",
    "title": "Fastest to 100 customers",
    "category": "records-speed",
    "creator": "Nelly Agbogu",
    "achievement": "The shortest time from a creator's first sale to their hundredth distinct customer.",
    "description": "Counted by customer, not by order — repeat buyers from the same person only count once.",
    "figure": {
      "value": "0 Days",
      "label": "5 January 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Isaac Oyedepo",
        "figure": "0 Days",
        "date": "Dec 17, 2024",
        "photo": "/exhibition/creators/isaac-oyedepo1-selar-com-20250312020328.jpg",
        "storeUrl": "https://selar.com/m/isaac-oyedepo1"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Ernest Opoku Appah",
        "figure": "0 Days",
        "date": "Jan 4, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/ernest-opoku-appah1"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Sisi Yemmie",
        "figure": "1 Day",
        "date": "Dec 21, 2020",
        "photo": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
        "storeUrl": "https://selar.com/m/Sisiyemmie"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Jennifer Awirigwe",
        "figure": "1 Day",
        "date": "Jun 30, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/FinancialJennifer"
      }
    ],
    "pastHolders": [],
    "displayDate": "5 January 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 104,
    "date": "2021-01-05",
    "datePrecision": "day"
  },
  {
    "id": "rec-006",
    "slug": "record-fastest-to-1000-customers",
    "title": "Fastest to 1,000 customers",
    "category": "records-speed",
    "creator": "Nelly Agbogu",
    "achievement": "The shortest time from first sale to one thousand distinct customers.",
    "description": "The jump from a hundred to a thousand is where most creators move from selling to an audience they already had to selling to one they had to build.",
    "figure": {
      "value": "1 Day",
      "label": "6 January 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Baohfo Fadibo",
        "figure": "5 Days",
        "date": "Mar 25, 2025",
        "photo": null,
        "storeUrl": "https://selar.com/m/baohfo-fadibo1"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Maltida  Oseze",
        "figure": "11 Days",
        "date": "Sep 1, 2025",
        "photo": "/exhibition/creators/maltida-oseze1-selar-com-20251213090837.jpg",
        "storeUrl": "https://selar.com/m/maltida-oseze1"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "BO BRAND",
        "figure": "18 Days",
        "date": "Oct 7, 2023",
        "photo": "/exhibition/creators/nwankwo-chinonso1-selar-com-20260613040236.jpg",
        "storeUrl": "https://Bomasterclass.selar.com/shop"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "TTP Digital",
        "figure": "19 Days",
        "date": "Feb 1, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/ttp-digital0"
      }
    ],
    "pastHolders": [],
    "displayDate": "6 January 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 105,
    "date": "2021-01-06",
    "datePrecision": "day"
  },
  {
    "id": "rec-007",
    "slug": "record-fastest-to-10000-customers",
    "title": "Fastest to 10,000 customers",
    "category": "records-speed",
    "creator": "Nelly Agbogu",
    "achievement": "The shortest time from first sale to ten thousand distinct customers — the largest audience milestone in the book.",
    "description": "Every holder to date has reached it with a product priced under $20.",
    "figure": {
      "value": "166 Days",
      "label": "20 June 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "CentralAfCo™",
        "figure": "439 Days",
        "date": "Oct 17, 2024",
        "photo": "/exhibition/creators/godfrey-mato1-selar-co-20231203050730.jpg",
        "storeUrl": "https://selar.com/m/CentralAfiCo"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "charisma Secrets",
        "figure": "495 Days",
        "date": "Sep 17, 2026",
        "photo": "/exhibition/creators/charismasecrets-selar-com-20250527011426.jpg",
        "storeUrl": "https://selar.com/m/charismasecrets"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "COACH DINO",
        "figure": "549 Days",
        "date": "Dec 30, 2023",
        "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
        "storeUrl": "https://dailyimcomeblueprint.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Taofeek Kareem",
        "figure": "603 Days",
        "date": "Jul 30, 2023",
        "photo": null,
        "storeUrl": "https://7figureaffiliate.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "20 June 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 106,
    "date": "2021-06-20",
    "datePrecision": "day"
  },
  {
    "id": "rec-008",
    "slug": "record-longest-daily-sales-streak",
    "title": "Longest daily sales streak",
    "category": "records-streaks",
    "creator": "COACH DINO",
    "achievement": "The longest unbroken run of days on which a creator made at least one sale.",
    "description": "A single day without a sale ends the streak, so it measures consistency rather than scale — several holders have never had a record month.",
    "figure": {
      "value": "1,194 Days",
      "label": "15 August 2026"
    },
    "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
    "storeUrl": "https://dailyimcomeblueprint.selar.com/",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "The Intentional Parent Academy",
        "figure": "1,084 Days",
        "date": "Ongoing",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "CentralAfCo™",
        "figure": "1,015 Days",
        "date": "Ongoing",
        "photo": "/exhibition/creators/godfrey-mato1-selar-co-20231203050730.jpg",
        "storeUrl": "https://selar.com/m/CentralAfiCo"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Victor Nathel",
        "figure": "872 Days",
        "date": "Ongoing",
        "photo": "/exhibition/creators/victornathel-selar-co-20230406082832.jpg",
        "storeUrl": "https://victornathel.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Sisi Yemmie",
        "figure": "751 Days",
        "date": "Dec 2, 2023",
        "photo": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
        "storeUrl": "https://selar.com/m/Sisiyemmie"
      }
    ],
    "pastHolders": [],
    "displayDate": "15 August 2026",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 107,
    "date": "2026-08-15",
    "datePrecision": "day"
  },
  {
    "id": "rec-009",
    "slug": "record-longest-monthly-sales-streak",
    "title": "Longest monthly sales streak",
    "category": "records-streaks",
    "creator": "Tolu Falode",
    "achievement": "The longest unbroken run of calendar months in which a creator made at least one sale.",
    "description": "The slower cousin of the daily streak, and the only record here measured in years rather than days.",
    "figure": {
      "value": "98 Months",
      "label": "Ongoing since August 2018"
    },
    "photo": "/exhibition/creators/tolu-selar-com-20251219093120.jpg",
    "storeUrl": "https://selar.com/m/Tolu",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Olabisi Ola-Soetan",
        "figure": "71 Months",
        "date": "Ongoing",
        "photo": null,
        "storeUrl": "https://secretplacewife.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "The Intentional Parent Academy",
        "figure": "70 Months",
        "date": "Ongoing",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Sisi Yemmie",
        "figure": "70 Months",
        "date": "Ongoing",
        "photo": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
        "storeUrl": "https://selar.com/m/Sisiyemmie"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "SUPERNATURAL MARRIAGE NETWORK",
        "figure": "68 Months",
        "date": "Ongoing",
        "photo": "/exhibition/creators/supernaturalmarriagenetwork-selar-com-20260727031631.jpg",
        "storeUrl": "https://supernaturalmarriagenetwork.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "Ongoing since August 2018",
    "ongoing": true,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 108
  },
  {
    "id": "rec-010",
    "slug": "record-highest-monthly-revenue",
    "title": "Highest single-month revenue",
    "category": "records-volume",
    "creator": "Isi Benedicta Institute",
    "achievement": "The most revenue a creator has taken in one calendar month.",
    "description": "Unlike the “fastest to” records this one has no ceiling, so it is the record most likely to be standing again by this time next year.",
    "figure": {
      "value": "$144,434.01",
      "label": "September 2025"
    },
    "photo": "/exhibition/creators/isibenedicta-selar-co-20230417095955.jpg",
    "storeUrl": "https://selar.com/m/isibenedicta",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "BO BRAND",
        "figure": "$109,806.12",
        "date": "Oct 2023",
        "photo": "/exhibition/creators/nwankwo-chinonso1-selar-com-20260613040236.jpg",
        "storeUrl": "https://Bomasterclass.selar.com/shop"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Dr. Sam Adeyemi",
        "figure": "$95,172.68",
        "date": "Feb 2026",
        "photo": "/exhibition/creators/drsamadeyemi-selar-com-20260820105445.jpg",
        "storeUrl": "https://samadeyemi.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Tara  Fela Durotoye",
        "figure": "$78,489.63",
        "date": "Sep 2026",
        "photo": null,
        "storeUrl": "https://tarafeladurotoye.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Discovery Centre",
        "figure": "$76,273.48",
        "date": "Dec 2025",
        "photo": "/exhibition/creators/thediscoverycentre-selar-co-20230729052438.jpg",
        "storeUrl": "https://thediscoverycentre.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "September 2025",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 109,
    "date": "2025-09",
    "datePrecision": "month"
  },
  {
    "id": "rec-011",
    "slug": "record-most-units-in-a-month",
    "title": "Most units sold in a month",
    "category": "records-volume",
    "creator": "Oreint Graphic Skills",
    "achievement": "The most individual units sold in one calendar month, counted per item rather than per order.",
    "description": "It rewards volume over price, and has never been held by the same creator two years running.",
    "figure": {
      "value": "8,133 Units",
      "label": "January 2026"
    },
    "photo": "/exhibition/creators/salesaffilate-selar-com-20260118093828.jpg",
    "storeUrl": "https://selar.com/m/Orientskills",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Nelly Agbogu",
        "figure": "6,412 Units",
        "date": "Jan 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Oluwafemi Williams",
        "figure": "4,731 Units",
        "date": "Jan 2024",
        "photo": "/exhibition/creators/aoh14gjcgwmzuymyvwklndsfdmyjyghfvcl-p2j6egn2uhs-s96-c.jpg",
        "storeUrl": "https://selar.com/m/theexcellon"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "COACH DINO",
        "figure": "4,178 Units",
        "date": "Dec 2024",
        "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
        "storeUrl": "https://dailyimcomeblueprint.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Intentional Parent Academy",
        "figure": "4,062 Units",
        "date": "Dec 2025",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "January 2026",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 110,
    "date": "2026-01",
    "datePrecision": "month"
  },
  {
    "id": "rec-012",
    "slug": "record-highest-monthly-growth",
    "title": "Highest month-over-month revenue growth",
    "category": "records-volume",
    "creator": "Tara Fela Durotoye",
    "achievement": "The largest month-over-month jump in revenue, measured as a percentage against the creator's previous month.",
    "description": "It is the one record here that a small account can take from a large one, which is why it turns over most often.",
    "figure": {
      "value": "+2607.7%",
      "label": "August 2025"
    },
    "photo": null,
    "storeUrl": "https://tarafeladurotoye.selar.com/",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Tricia Biz",
        "figure": "+1985.6%",
        "date": "Apr 2023",
        "photo": null,
        "storeUrl": "https://triciabiz.selar.com/shop"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Learning  Lantern",
        "figure": "+1730.7%",
        "date": "Aug 2025",
        "photo": null,
        "storeUrl": "https://selar.com/m/learning-lantern1"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Isi Benedicta Institute",
        "figure": "+1704.9%",
        "date": "Jul 2025",
        "photo": "/exhibition/creators/isibenedicta-selar-co-20230417095955.jpg",
        "storeUrl": "https://selar.com/m/isibenedicta"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "ForXers",
        "figure": "+1517.3%",
        "date": "May 2025",
        "photo": "/exhibition/creators/nzoputa-ezike1-selar-com-20250611070749.jpg",
        "storeUrl": "https://ForXers.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "August 2025",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 111,
    "date": "2025-08",
    "datePrecision": "month"
  },
  {
    "id": "rec-013",
    "slug": "record-most-sales-in-a-day",
    "title": "Most sales in a day",
    "category": "records-volume",
    "creator": "Promise Nicholas Akpan",
    "achievement": "The most orders a creator has taken in a single calendar day, paid and free alike.",
    "description": "It rewards launch-day clarity, offer strength, and the ability to turn attention into action quickly.",
    "figure": {
      "value": "2,538 Sales",
      "label": "30 September 2023"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/Fxsamurai",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Oluwafemi Williams",
        "figure": "2,248 Sales",
        "date": "Jan 13, 2024",
        "photo": "/exhibition/creators/aoh14gjcgwmzuymyvwklndsfdmyjyghfvcl-p2j6egn2uhs-s96-c.jpg",
        "storeUrl": "https://selar.com/m/theexcellon"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "The Intentional Parent Academy",
        "figure": "1,172 Sales",
        "date": "Jun 5, 2023",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Nelly Agbogu",
        "figure": "1,148 Sales",
        "date": "Jan 6, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "NaijaSales Maker",
        "figure": "1,104 Sales",
        "date": "May 13, 2025",
        "photo": "/exhibition/creators/naijasalesmaker-selar-com-20261004080602.jpg",
        "storeUrl": "https://naijasalesmaker.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "30 September 2023",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 112,
    "date": "2023-09-30",
    "datePrecision": "day"
  },
  {
    "id": "rec-014",
    "slug": "record-most-buyers-in-a-day",
    "title": "Most customers in a day",
    "category": "records-volume",
    "creator": "Promise Nicholas Akpan",
    "achievement": "The most distinct customers a creator has sold to in a single calendar day.",
    "description": "Repeat orders do not pad the count, so every number represents a real buyer.",
    "figure": {
      "value": "2,538 Customers",
      "label": "30 September 2023"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/Fxsamurai",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Oluwafemi Williams",
        "figure": "2,248 Customers",
        "date": "Jan 13, 2024",
        "photo": "/exhibition/creators/aoh14gjcgwmzuymyvwklndsfdmyjyghfvcl-p2j6egn2uhs-s96-c.jpg",
        "storeUrl": "https://selar.com/m/theexcellon"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "The Intentional Parent Academy",
        "figure": "1,172 Customers",
        "date": "Jun 5, 2023",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Nelly Agbogu",
        "figure": "1,148 Customers",
        "date": "Jan 6, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "NaijaSales Maker",
        "figure": "1,104 Customers",
        "date": "May 13, 2025",
        "photo": "/exhibition/creators/naijasalesmaker-selar-com-20261004080602.jpg",
        "storeUrl": "https://naijasalesmaker.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "30 September 2023",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 113,
    "date": "2023-09-30",
    "datePrecision": "day"
  },
  {
    "id": "rec-015",
    "slug": "record-most-orders-in-a-week",
    "title": "Most orders in a week",
    "category": "records-volume",
    "creator": "Promise Nicholas Akpan",
    "achievement": "The most orders a creator has taken across any seven consecutive days.",
    "description": "",
    "figure": {
      "value": "3,624 Sales",
      "label": "1 October 2023"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/Fxsamurai",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Nelly Agbogu",
        "figure": "3,579 Sales",
        "date": "Jan 10, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Oluwafemi Williams",
        "figure": "3,503 Sales",
        "date": "Jan 14, 2024",
        "photo": "/exhibition/creators/aoh14gjcgwmzuymyvwklndsfdmyjyghfvcl-p2j6egn2uhs-s96-c.jpg",
        "storeUrl": "https://selar.com/m/theexcellon"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "The Intentional Parent Academy",
        "figure": "2,578 Sales",
        "date": "Dec 7, 2025",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "NaijaSales Maker",
        "figure": "2,374 Sales",
        "date": "May 18, 2025",
        "photo": "/exhibition/creators/naijasalesmaker-selar-com-20261004080602.jpg",
        "storeUrl": "https://naijasalesmaker.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "1 October 2023",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 114,
    "date": "2023-10-01",
    "datePrecision": "day"
  },
  {
    "id": "rec-016",
    "slug": "record-most-returning-customers",
    "title": "Highest returning-customer share",
    "category": "records-streaks",
    "creator": "Hafusat Jubreel",
    "achievement": "The highest share of a month's customers who had bought from the creator before.",
    "description": "",
    "figure": {
      "value": "86.5%",
      "label": "30 September 2026"
    },
    "photo": "/exhibition/creators/hafusat-jubreel1-selar-com-20250626082101.jpg",
    "storeUrl": "https://selar.com/m/hafusat-jubreel1",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "IPNET Global",
        "figure": "84.9%",
        "date": "Sep 30, 2026",
        "photo": "/exhibition/creators/ipnetglobal-selar-com-20250304120401.jpg",
        "storeUrl": "https://selar.com/m/ipnetglobal"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "The Pitch STHRIM (Survive, Thrive, Multiply)",
        "figure": "81.7%",
        "date": "Apr 5, 2026",
        "photo": "/exhibition/creators/acg8ocka1lc69lttty-iu-a2bhm7fox8wyjtcg8iejmhh7puza-s96-c.jpg",
        "storeUrl": "https://selar.com/m/thepitchsthrim-survive-thrive-multiply"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Victor Joshua",
        "figure": "81%",
        "date": "Mar 9, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/Joshspot"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Nse Umoh-Daniel",
        "figure": "76.8%",
        "date": "Jun 18, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/YoungNse"
      }
    ],
    "pastHolders": [],
    "displayDate": "30 September 2026",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 115,
    "date": "2026-09-30",
    "datePrecision": "day"
  },
  {
    "id": "rec-017",
    "slug": "record-creator-of-the-year",
    "title": "Creator of the Year",
    "category": "records-honour",
    "creator": "COACH DINO",
    "achievement": "The Selar record for creator of the Year.",
    "description": "",
    "figure": {
      "value": "21,085 Sales",
      "label": "2025"
    },
    "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
    "storeUrl": "https://dailyimcomeblueprint.selar.com/",
    "runnerUps": [],
    "pastHolders": [
      {
        "name": "COACH DINO",
        "stat": "22,059 Sales · 2024",
        "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
        "storeUrl": "https://dailyimcomeblueprint.selar.com/"
      },
      {
        "name": "COACH DINO",
        "stat": "8,759 Sales · 2023",
        "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
        "storeUrl": "https://dailyimcomeblueprint.selar.com/"
      },
      {
        "name": "Taofeek Kareem",
        "stat": "8,926 Sales · 2022",
        "photo": null,
        "storeUrl": "https://7figureaffiliate.selar.com/"
      },
      {
        "name": "Nelly Agbogu",
        "stat": "17,961 Sales · 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      },
      {
        "name": "Tricia Biz",
        "stat": "612 Sales · 2020",
        "photo": null,
        "storeUrl": "https://triciabiz.selar.com/shop"
      },
      {
        "name": "EXQUISITE MAGAZINE",
        "stat": "185 Sales · 2019",
        "photo": null,
        "storeUrl": "https://selar.com/m/exquisitemag"
      },
      {
        "name": "Outburst Music Group",
        "stat": "354 Sales · 2018",
        "photo": null,
        "storeUrl": "https://selar.com/m/OutburstMusicGroup"
      }
    ],
    "displayDate": "2025",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 116,
    "date": "2025",
    "datePrecision": "year"
  },
  {
    "id": "rec-018",
    "slug": "record-first-show-love-contribution",
    "title": "First Show Love contribution",
    "category": "records-firsts",
    "creator": "James Karundu",
    "achievement": "The Selar record for first Show Love contribution.",
    "description": "",
    "figure": {
      "value": "2 Contributions",
      "label": "23 December 2023"
    },
    "photo": "/exhibition/creators/jameskarundu-selar-co-20231222021403.jpg",
    "storeUrl": "https://jameskarundu.selar.com/",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Ayomide daniel",
        "figure": "1 Contribution",
        "date": "Dec 23, 2023",
        "photo": "/exhibition/creators/hollygrafix-selar-co-20231221034321.jpg",
        "storeUrl": "https://selar.com/m/Hollygrafix"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Benny Growth Hub",
        "figure": "1 Contribution",
        "date": "Dec 24, 2023",
        "photo": "/exhibition/creators/bennyexpression-selar-com-20260129095729.jpg",
        "storeUrl": "https://selar.com/m/Bennyexpression"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Emeka Nobis",
        "figure": "7 Contributions",
        "date": "Dec 25, 2023",
        "photo": "/exhibition/creators/emekanobis-selar-co-20231225092830.jpg",
        "storeUrl": "https://emekanobis.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Irene Pepple",
        "figure": "2 Contributions",
        "date": "Dec 25, 2023",
        "photo": "/exhibition/creators/aoh14girpdr8pl1gukhjj-3okq1gatr1qlvcvdeflt1far4-s96-c.jpg",
        "storeUrl": "https://IniIrenePepple.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "23 December 2023",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 117,
    "date": "2023-12-23",
    "datePrecision": "day"
  },
  {
    "id": "rec-019",
    "slug": "record-first-affiliate-commission",
    "title": "First affiliate commission paid",
    "category": "records-firsts",
    "creator": "Ajiboye Temitope",
    "achievement": "The Selar record for first affiliate commission paid.",
    "description": "",
    "figure": {
      "value": "$5.58",
      "label": "21 August 2017"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/tayormi",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Julchit Dadi",
        "figure": "$0.39",
        "date": "Mar 4, 2018",
        "photo": null,
        "storeUrl": "https://selar.com/m/JazzEntrepreneur"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "George Okoro",
        "figure": "$0.36",
        "date": "Sep 14, 2018",
        "photo": null,
        "storeUrl": "https://selar.com/m/GeorgeOkoro"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Chocolate City",
        "figure": "$1.26",
        "date": "Sep 21, 2018",
        "photo": null,
        "storeUrl": "https://selar.com/m/ChocolateCityMusic"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "EXQUISITE MAGAZINE",
        "figure": "$2.16",
        "date": "Feb 2, 2019",
        "photo": null,
        "storeUrl": "https://selar.com/m/exquisitemag"
      }
    ],
    "pastHolders": [],
    "displayDate": "21 August 2017",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 118,
    "date": "2017-08-21",
    "datePrecision": "day"
  },
  {
    "id": "rec-020",
    "slug": "record-first-ticket-sold",
    "title": "First event ticket sold",
    "category": "records-firsts",
    "creator": "Omosi Ng",
    "achievement": "The Selar record for first event ticket sold.",
    "description": "",
    "figure": {
      "value": "1 Ticket",
      "label": "11 June 2024"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/omosi-ng1",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "AYF EGBA DIOCESE",
        "figure": "1 Ticket",
        "date": "Jun 12, 2024",
        "photo": null,
        "storeUrl": "https://selar.com/m/ayfegbadiocese2023"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Gbolahan Yussuf Hammed",
        "figure": "5 Tickets",
        "date": "Jun 13, 2024",
        "photo": "/exhibition/creators/aitbvmnhiaxrmhhi4ity5lbsvdcni56nrbod2zdr-1nf-s96-c.jpg",
        "storeUrl": "https://selar.com/m/gbolahanyussufhammed"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Frank iTom",
        "figure": "4 Tickets",
        "date": "Jun 13, 2024",
        "photo": "/exhibition/creators/frank-itom1-selar-co-20240326071255.jpg",
        "storeUrl": "https://FrankiTom.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Chai with SoulUnraveled",
        "figure": "1 Ticket",
        "date": "Jun 15, 2024",
        "photo": "/exhibition/creators/chaiwithsoulunraveled-selar-co-20230225023056.jpg",
        "storeUrl": "https://selar.com/m/chaiwithsoulunraveled"
      }
    ],
    "pastHolders": [],
    "displayDate": "11 June 2024",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 119,
    "date": "2024-06-11",
    "datePrecision": "day"
  },
  {
    "id": "rec-021",
    "slug": "record-first-to-10000-sales",
    "title": "First to 10,000 sales",
    "category": "records-firsts",
    "creator": "Nelly Agbogu",
    "achievement": "The Selar record for first to 10,000 sales.",
    "description": "",
    "figure": {
      "value": "10,142 Sales",
      "label": "17 June 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Taofeek Kareem",
        "figure": "10,001 Sales",
        "date": "Jun 20, 2023",
        "photo": null,
        "storeUrl": "https://7figureaffiliate.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Sisi Yemmie",
        "figure": "10,013 Sales",
        "date": "Oct 20, 2023",
        "photo": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
        "storeUrl": "https://selar.com/m/Sisiyemmie"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Emeka Nobis",
        "figure": "10,109 Sales",
        "date": "Nov 24, 2023",
        "photo": "/exhibition/creators/emekanobis-selar-co-20231225092830.jpg",
        "storeUrl": "https://emekanobis.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Intentional Parent Academy",
        "figure": "10,010 Sales",
        "date": "Dec 3, 2023",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "17 June 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 120,
    "date": "2021-06-17",
    "datePrecision": "day"
  },
  {
    "id": "rec-022",
    "slug": "record-first-365-day-streak",
    "title": "First 365-day sales streak",
    "category": "records-streaks",
    "creator": "Sisi Yemmie",
    "achievement": "The Selar record for first 365-day sales streak.",
    "description": "",
    "figure": {
      "value": "365 Days",
      "label": "11 November 2022"
    },
    "photo": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
    "storeUrl": "https://selar.com/m/Sisiyemmie",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Taofeek Kareem",
        "figure": "365 Days",
        "date": "Jan 18, 2023",
        "photo": null,
        "storeUrl": "https://7figureaffiliate.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "COACH DINO",
        "figure": "365 Days",
        "date": "May 8, 2024",
        "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
        "storeUrl": "https://dailyimcomeblueprint.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Unique Affiliate Community",
        "figure": "365 Days",
        "date": "Jun 17, 2024",
        "photo": "/exhibition/creators/maxdivine-selar-co-20220912113413.jpg",
        "storeUrl": "https://selar.com/m/Maxdivine"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Intentional Parent Academy",
        "figure": "365 Days",
        "date": "Oct 20, 2024",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "11 November 2022",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 121,
    "date": "2022-11-11",
    "datePrecision": "day"
  },
  {
    "id": "rec-023",
    "slug": "record-first-to-sell-in-50-countries",
    "title": "First to sell in 50 countries",
    "category": "records-firsts",
    "creator": "Nelly Agbogu",
    "achievement": "The Selar record for first to sell in 50 countries.",
    "description": "",
    "figure": {
      "value": "50 Countries",
      "label": "4 June 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Sisi Yemmie",
        "figure": "50 Countries",
        "date": "Aug 2, 2021",
        "photo": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
        "storeUrl": "https://selar.com/m/Sisiyemmie"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Jennifer Awirigwe",
        "figure": "50 Countries",
        "date": "May 27, 2022",
        "photo": null,
        "storeUrl": "https://selar.com/m/FinancialJennifer"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Godwin Edafe Oghenekome",
        "figure": "50 Countries",
        "date": "Jun 7, 2022",
        "photo": "/exhibition/creators/fxtradersdelight-selar-co-20221020081636.jpg",
        "storeUrl": "https://selar.com/m/fxtdacademy"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Zarahdoughnuts",
        "figure": "50 Countries",
        "date": "Jun 22, 2022",
        "photo": "/exhibition/creators/zarahdoughnuts-selar-co-20211222092715.jpg",
        "storeUrl": "https://selar.com/m/Zarahdoughnuts"
      }
    ],
    "pastHolders": [],
    "displayDate": "4 June 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 122,
    "date": "2021-06-04",
    "datePrecision": "day"
  },
  {
    "id": "rec-024",
    "slug": "record-first-course-sold",
    "title": "First creator to sell a course on Selar",
    "category": "records-firsts",
    "creator": "HABEEBAH CAKES",
    "achievement": "The Selar record for first creator to sell a course on Selar.",
    "description": "",
    "figure": {
      "value": "2 Sales",
      "label": "1 November 2020"
    },
    "photo": "/exhibition/creators/habeebahcakes-selar-co-20240704091114.jpg",
    "storeUrl": "https://habeebahcakes.selar.com/",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Products by Dele Amaebite",
        "figure": "1 Sale",
        "date": "Nov 9, 2020",
        "photo": "/exhibition/creators/deleamaebite-selar-co-20220820010236.jpg",
        "storeUrl": "https://deleamaebite.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Smartphonephotographyboss",
        "figure": "2 Sales",
        "date": "Nov 12, 2020",
        "photo": "/exhibition/creators/smartphonephotographyboss-selar-co-20221006093758.jpg",
        "storeUrl": "https://smartphonephotographyboss.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Temitope Akintoye (Trendy Courier)",
        "figure": "1 Sale",
        "date": "Nov 12, 2020",
        "photo": "/exhibition/creators/temitopeakintoye-selar-co-20230827122043.jpg",
        "storeUrl": "https://trendycourieracademy.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "HOUSEOFMASCOT",
        "figure": "2 Sales",
        "date": "Nov 20, 2020",
        "photo": "/exhibition/creators/houseofmascot-selar-co-20220115033458.jpg",
        "storeUrl": "https://houseofmascot.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "1 November 2020",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 123,
    "date": "2020-11-01",
    "datePrecision": "day"
  },
  {
    "id": "rec-025",
    "slug": "record-first-to-1000-digital-products",
    "title": "First to 1,000 digital products sold",
    "category": "records-firsts",
    "creator": "Nelly Agbogu",
    "achievement": "The Selar record for first to 1,000 digital products sold.",
    "description": "",
    "figure": {
      "value": "1,317 Units",
      "label": "6 January 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Emeka Nobis",
        "figure": "1,032 Units",
        "date": "Feb 19, 2021",
        "photo": "/exhibition/creators/emekanobis-selar-co-20231225092830.jpg",
        "storeUrl": "https://emekanobis.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Sisi Yemmie",
        "figure": "1,011 Units",
        "date": "Mar 3, 2021",
        "photo": "/exhibition/creators/sisiyemmie-selar-co-20220115071825.jpg",
        "storeUrl": "https://selar.com/m/Sisiyemmie"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "The Intentional Parent Academy",
        "figure": "1,003 Units",
        "date": "Dec 17, 2021",
        "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
        "storeUrl": "https://theintentionalparentacademy.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Emisphere Catering",
        "figure": "1,017 Units",
        "date": "Jan 23, 2022",
        "photo": "/exhibition/creators/aoh14ginfbfzxpdtxch9cvihjq7uea9gmqi2smbigsif-s96-c.jpg",
        "storeUrl": "https://emispherefoods.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "6 January 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 124,
    "date": "2021-01-06",
    "datePrecision": "day"
  },
  {
    "id": "rec-026",
    "slug": "record-first-to-100k-course-sales",
    "title": "First to $100K in course sales",
    "category": "records-firsts",
    "creator": "Taofeek Kareem",
    "achievement": "The Selar record for first to $100K in course sales.",
    "description": "",
    "figure": {
      "value": "$100,004.88",
      "label": "21 September 2022"
    },
    "photo": null,
    "storeUrl": "https://7figureaffiliate.selar.com/",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "NaijaSales Maker",
        "figure": "$100,022.31",
        "date": "Oct 14, 2022",
        "photo": "/exhibition/creators/naijasalesmaker-selar-com-20261004080602.jpg",
        "storeUrl": "https://naijasalesmaker.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Jackto Precious",
        "figure": "$100,197.47",
        "date": "Jul 1, 2024",
        "photo": null,
        "storeUrl": "https://cryptprokit.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Victor Nathel",
        "figure": "$100,015.31",
        "date": "Oct 6, 2024",
        "photo": "/exhibition/creators/victornathel-selar-co-20230406082832.jpg",
        "storeUrl": "https://victornathel.selar.com/"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "COACH DINO",
        "figure": "$100,612.25",
        "date": "Dec 22, 2024",
        "photo": "/exhibition/creators/odogwudino1-selar-co-20240108063656.jpg",
        "storeUrl": "https://dailyimcomeblueprint.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "21 September 2022",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 125,
    "date": "2022-09-21",
    "datePrecision": "day"
  },
  {
    "id": "rec-027",
    "slug": "record-first-digital-bundle-sold",
    "title": "First digital bundle sold",
    "category": "records-firsts",
    "creator": "Smart Bride Hub by Pearls",
    "achievement": "The Selar record for first digital bundle sold.",
    "description": "",
    "figure": {
      "value": "1 Sale",
      "label": "10 February 2026"
    },
    "photo": "/exhibition/creators/faith-adeniyi2198938-selar-com-20260214092122.jpg",
    "storeUrl": "https://selar.com/m/smartbridehubbypearls",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Colors of Hope Global",
        "figure": "1 Sale",
        "date": "Feb 16, 2026",
        "photo": "/exhibition/creators/colorsofhopeglobal-selar-co-20230101102737.jpg",
        "storeUrl": "https://selar.com/m/Colorsofhopeglobal"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "5StarMums",
        "figure": "1 Sale",
        "date": "Feb 19, 2026",
        "photo": "/exhibition/creators/5starmums-selar-com-20250513112654.jpg",
        "storeUrl": "https://selar.com/m/5starmums"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Babafemi Adebajo",
        "figure": "2 Sales",
        "date": "Feb 22, 2026",
        "photo": "/exhibition/creators/babafemi-adebajo-selar-com-20260714031718.jpg",
        "storeUrl": "https://selar.com/m/babafemi-adebajo"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Alpha Kids Mentorship",
        "figure": "1 Sale",
        "date": "Feb 23, 2026",
        "photo": "/exhibition/creators/akuasafo-selar-com-20260210044749.jpg",
        "storeUrl": "https://selar.com/m/alphakids"
      }
    ],
    "pastHolders": [],
    "displayDate": "10 February 2026",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 126,
    "date": "2026-02-10",
    "datePrecision": "day"
  },
  {
    "id": "rec-028",
    "slug": "record-first-to-3000-physical-products",
    "title": "First to 3,000 physical products sold",
    "category": "records-firsts",
    "creator": "The Intentional Parent Academy",
    "achievement": "The Selar record for first to 3,000 physical products sold.",
    "description": "",
    "figure": {
      "value": "3,000 Units",
      "label": "7 June 2025"
    },
    "photo": "/exhibition/creators/theintentionalparentacademy-selar-co-20240528120827.jpg",
    "storeUrl": "https://theintentionalparentacademy.selar.com/",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Talk Dirty Online Shop",
        "figure": "3,010 Units",
        "date": "May 15, 2026",
        "photo": "/exhibition/creators/copy-of-talkshop-20260303-220904-0000-20260811050319.jpg",
        "storeUrl": "https://TalkShop.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "7 June 2025",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 127,
    "date": "2025-06-07",
    "datePrecision": "day"
  },
  {
    "id": "rec-029",
    "slug": "record-first-to-10k-from-memberships",
    "title": "First to $10K from memberships",
    "category": "records-firsts",
    "creator": "Kenny Nwokoye",
    "achievement": "The Selar record for first to $10K from memberships.",
    "description": "",
    "figure": {
      "value": "$10,167.94",
      "label": "28 June 2022"
    },
    "photo": "/exhibition/creators/kennynwokoye-selar-co-20231220033832.jpg",
    "storeUrl": "https://kennynwokoye.selar.com/",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Tolu Falode",
        "figure": "$10,862.26",
        "date": "Jul 11, 2025",
        "photo": "/exhibition/creators/tolu-selar-com-20251219093120.jpg",
        "storeUrl": "https://selar.com/m/Tolu"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "With Chude",
        "figure": "$10,014.87",
        "date": "Jun 14, 2026",
        "photo": "/exhibition/creators/withchude-selar-com-20250903050354.jpg",
        "storeUrl": "https://withchude.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "28 June 2022",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 128,
    "date": "2022-06-28",
    "datePrecision": "day"
  },
  {
    "id": "rec-030",
    "slug": "record-first-five-figure-launch",
    "title": "First five-figure launch",
    "category": "records-firsts",
    "creator": "Tricia Biz",
    "achievement": "The Selar record for first five-figure launch.",
    "description": "",
    "figure": {
      "value": "$15,451.94",
      "label": "18 August 2020"
    },
    "photo": null,
    "storeUrl": "https://triciabiz.selar.com/shop",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Steve Harris",
        "figure": "$17,963.39",
        "date": "Oct 15, 2020",
        "photo": null,
        "storeUrl": "https://iamsteveharris.selar.com/"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Products by Dele Amaebite",
        "figure": "$10,424.03",
        "date": "Dec 3, 2020",
        "photo": "/exhibition/creators/deleamaebite-selar-co-20220820010236.jpg",
        "storeUrl": "https://deleamaebite.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Nelly Agbogu",
        "figure": "$11,135.38",
        "date": "Jan 16, 2021",
        "photo": null,
        "storeUrl": "https://selar.com/m/DominatewithNBC"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "The Discovery Centre",
        "figure": "$14,421.84",
        "date": "Mar 30, 2021",
        "photo": "/exhibition/creators/thediscoverycentre-selar-co-20230729052438.jpg",
        "storeUrl": "https://thediscoverycentre.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "18 August 2020",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 129,
    "date": "2020-08-18",
    "datePrecision": "day"
  },
  {
    "id": "rec-031",
    "slug": "record-highest-course-launch-revenue",
    "title": "Highest course launch revenue",
    "category": "records-volume",
    "creator": "Nelly Agbogu",
    "achievement": "The Selar record for highest course launch revenue.",
    "description": "",
    "figure": {
      "value": "$43,528.30",
      "label": "23 November 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Catalyst Children Network",
        "figure": "$36,089.71",
        "date": "Aug 4, 2026",
        "photo": "/exhibition/creators/catalystnetwork-selar-com-20250926012439.jpg",
        "storeUrl": "https://selar.com/m/catalystchildrennetwork"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Mark Angel",
        "figure": "$21,067.35",
        "date": "Feb 6, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/mark-angel1"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Tricia Biz",
        "figure": "$16,480.49",
        "date": "Dec 29, 2021",
        "photo": null,
        "storeUrl": "https://triciabiz.selar.com/shop"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Ayanime Edem",
        "figure": "$11,582.30",
        "date": "Feb 19, 2026",
        "photo": "/exhibition/creators/ayanimeedem-selar-co-20220306033436.jpg",
        "storeUrl": "https://ayanimeedem.selar.com/"
      }
    ],
    "pastHolders": [],
    "displayDate": "23 November 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 130,
    "date": "2021-11-23",
    "datePrecision": "day"
  },
  {
    "id": "rec-032",
    "slug": "record-most-sales-from-one-launch",
    "title": "Most sales from one launch",
    "category": "records-volume",
    "creator": "Nelly Agbogu",
    "achievement": "The Selar record for most sales from one launch.",
    "description": "",
    "figure": {
      "value": "6,375 Sales",
      "label": "20 January 2021"
    },
    "photo": null,
    "storeUrl": "https://selar.com/m/DominatewithNBC",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Oluwafemi Williams",
        "figure": "4,734 Sales",
        "date": "Jan 29, 2024",
        "photo": "/exhibition/creators/aoh14gjcgwmzuymyvwklndsfdmyjyghfvcl-p2j6egn2uhs-s96-c.jpg",
        "storeUrl": "https://selar.com/m/theexcellon"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Jennifer Awirigwe",
        "figure": "2,877 Sales",
        "date": "Jan 8, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/FinancialJennifer"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Maltida  Oseze",
        "figure": "2,765 Sales",
        "date": "Sep 19, 2025",
        "photo": "/exhibition/creators/maltida-oseze1-selar-com-20251213090837.jpg",
        "storeUrl": "https://selar.com/m/maltida-oseze1"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "BO BRAND",
        "figure": "2,502 Sales",
        "date": "Feb 20, 2024",
        "photo": "/exhibition/creators/nwankwo-chinonso1-selar-com-20260613040236.jpg",
        "storeUrl": "https://Bomasterclass.selar.com/shop"
      }
    ],
    "pastHolders": [],
    "displayDate": "20 January 2021",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 131,
    "date": "2021-01-20",
    "datePrecision": "day"
  },
  {
    "id": "rec-033",
    "slug": "record-fastest-membership-growth",
    "title": "Fastest membership growth",
    "category": "records-speed",
    "creator": "Phoenixes City",
    "achievement": "The Selar record for fastest membership growth.",
    "description": "",
    "figure": {
      "value": "34 Members",
      "label": "9 October 2026"
    },
    "photo": "/exhibition/creators/phoenixescity-selar-com-20260922012048.jpg",
    "storeUrl": "https://phoenixes.city/",
    "runnerUps": [],
    "pastHolders": [],
    "displayDate": "9 October 2026",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 132,
    "date": "2026-10-09",
    "datePrecision": "day"
  },
  {
    "id": "rec-034",
    "slug": "record-first-creator-membership",
    "title": "First paid community membership",
    "category": "records-firsts",
    "creator": "nursetrendy",
    "achievement": "The Selar record for first paid community membership.",
    "description": "",
    "figure": {
      "value": "1 Member",
      "label": "10 August 2026"
    },
    "photo": "/exhibition/creators/nursetrendy-selar-com-20260715040321.jpg",
    "storeUrl": "https://selar.com/m/nursetrendy",
    "runnerUps": [
      {
        "place": 2,
        "placeLabel": "2nd",
        "name": "Praise Daniel",
        "figure": "1 Member",
        "date": "Aug 11, 2026",
        "photo": "/exhibition/creators/acg8ockcvmhi2-txz-qd2qalqtx3ctlb8527zrtk8xb4tzm0vr8wluhh-s96-c.jpg",
        "storeUrl": "https://selar.com/m/praisedanielnatx"
      },
      {
        "place": 3,
        "placeLabel": "3rd",
        "name": "Terainz Healthcare",
        "figure": "1 Member",
        "date": "Aug 20, 2026",
        "photo": null,
        "storeUrl": "https://terainzhealthcare.selar.com/"
      },
      {
        "place": 4,
        "placeLabel": "4th",
        "name": "Ignite Possibilities",
        "figure": "1 Member",
        "date": "Sep 3, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/ignite-possibilities1"
      },
      {
        "place": 5,
        "placeLabel": "5th",
        "name": "Folasade Abimbola",
        "figure": "1 Member",
        "date": "Sep 8, 2026",
        "photo": null,
        "storeUrl": "https://selar.com/m/88lately"
      }
    ],
    "pastHolders": [],
    "displayDate": "10 August 2026",
    "ongoing": false,
    "sourceNote": "records.selar.com/breakable-records (site data generated 2026-10-10T03:34:02Z).",
    "sortOrder": 133,
    "date": "2026-08-10",
    "datePrecision": "day"
  }
];
